SERVICES-1006 improve asset history elastic query
ElrondNetwork/nft-service pull request #733
Opened 2022-12-06 16:44 UTC by johnykes

2022-12-07 17:38 UTC, danielailie requested changes

2022-12-08 08:17 UTC, johnykes commented on src/modules/asset-history/assets-history.service.ts
Done

2022-12-08 08:17 UTC, johnykes commented on src/modules/asset-history/assets-history.service.ts
>    ): Promise<AssetHistoryLog[]> {
Done

2022-12-08 15:11 UTC, danielailie approved these changes

2022-12-12 09:05 UTC, johnykes commented on src/modules/asset-history/assets-history.service.ts
> +
Fixed.

2022-12-12 10:09 UTC, johnykes commented on src/modules/asset-history/assets-history-elastic.service.ts
> +    private readonly elrondElasticService: ElrondElasticService, // @Inject(forwardRef(() => AssetsHistoryService)) // private readonly assetsHistoryService: AssetsHistoryService,
Done.

2022-12-12 10:11 UTC, danielailie approved these changes

2022-12-12 12:08 UTC, danielailie approved these changes

2022-12-12 12:10 UTC, merged